version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: municipal_postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - municipal_network
    restart: unless-stopped

  # Laravel Web Application (Backend + Frontend)
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: municipal_laravel
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./laravel:/var/www/html
      - laravel_storage:/var/www/html/storage
      - laravel_bootstrap:/var/www/html/bootstrap/cache
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - PYTHON_AI_SERVICE_URL=http://python-ai:8000
    depends_on:
      - postgres
    networks:
      - municipal_network
    restart: unless-stopped

  # Python AI Processing Service
  python-ai:
    build:
      context: ./python-ai
      dockerfile: Dockerfile
    container_name: municipal_python_ai
    ports:
      - "${PYTHON_AI_PORT}:8000"
    volumes:
      - ./python-ai:/app
      - ai_models:/app/models
      - ai_temp:/app/temp
    environment:
      - FLASK_ENV=${PYTHON_AI_ENV}
      - MODEL_PATH=/app/models
      - TEMP_PATH=/app/temp
    networks:
      - municipal_network
    restart: unless-stopped

  # Redis for caching and queues
  redis:
    image: redis:7-alpine
    container_name: municipal_redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - municipal_network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: municipal_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - laravel
    networks:
      - municipal_network
    restart: unless-stopped

networks:
  municipal_network:
    driver: bridge

volumes:
  postgres_data:
  laravel_storage:
  laravel_bootstrap:
  ai_models:
  ai_temp:
  redis_data: